GET localhost:8080/api/users/tobiasras
###

POST localhost:8080/api/users/tobiasras
Content-Type: application/json

{
  "company_name": "tobiasras",
  "name": "updatedUser",
  "username": "tobiaasdasdasdasdasd",
  "password": "123com",
  "email": "Radaasdasdasdasdsa@gmail.com"
}

###

POST localhost:8080/api/companies/
content-Type: application/json

{
  "cvr": "2518234912",
  "company_name": "tobiasras",
  "users": []
}

###

PUT localhost:8080/api/users/tobiasras/tobiaasdasd
Content-Type: application/json

{
  "company_name": "tobiasras",
  "name": "updatedUser5012asdasdasd3123123",
  "username": "tobiaasdasd",
  "password": "123142123123",
  "email": "Rasdasdad@gmail.com"
}
###

DELETE localhost:8080/api/users/tobiaasdasdasd
###



PUT localhost:8080/api/users/tobiasras/tobiaqsad
Content-Type: application/json

{
  "name": "fuckfuckfuck",
  "password": "123565com"
}
###

PUT localhost:8080/api/users/tobiasras/tobiaqsad
Content-Type: application/json

{
  "name": "updatedUser50123123123",
  "password": "123com",
  "email": "R51231@gmail.com"
}
###

PUT localhost:8080/api/users/tobiasras/tobiaqsad
Content-Type: application/json

{
  "name": "updatedUser50123123123",
  "username": "5123tobiaasdasd",
  "password": "123com",
  "email": "R51231dasd@gmail.com"
}
###